.travis.yml

travis: added coveralls

---

README.md

project: added README with basic uhu usage

---

tests/cli/test_pull.py
tests/object/test_upload.py
tests/package/test_push.py
tests/utils.py
uhu/core/_base.py
uhu/core/package.py

These are minor updates regarding API changes, such as response format, status code and etc...

Update uhu to latest API server specifications

---

tests/package/test_serialization.py
uhu/core/package.py

dot-uhu: added a new line character at the end of file when dumping

---

README.md

README: updated supported hardware related documentation

---

uhu/cli/__init__.py

docs: added documentation regarding API server address

---

tests/repl/test_validators.py

tests: increased coverage for uhu.repl.validators

---

setup.py

setup.py: sets min version for updatehub-package-schema package

---

tests/package/test_serialization.py
uhu/core/utils.py

uhupkg: change archive format to zipfile

---

tests/cli/test_pull.py
tests/http_/test_request.py
tests/object/test_download.py
tests/package/test_pull.py
tests/package/test_push.py
uhu/cli/package.py
uhu/core/_object.py
uhu/core/package.py
uhu/core/storages.py
uhu/http/__init__.py
uhu/http/_request.py
uhu/http/auth.py

http: created a better http wrapper to deal with exceptions

---

uhu/__init__.py

project: bump to version 1.0.0a2

---

tests/updatehub/test_http.py
uhu/updatehub/_request.py
uhu/updatehub/api.py
uhu/updatehub/http.py

- added timeout for all requests
- removed unused functions
- increased test coverage to 100%

http: small improvements on main updatehub http interface

---

tests/updatehub/test_http.py
uhu/updatehub/_request.py
uhu/updatehub/http.py

updatehub: increased http requests timeout

---

tests/repl/test_validators.py
uhu/core/_object.py
uhu/core/_options.py
uhu/core/validators.py
uhu/repl/helpers.py
uhu/repl/validators.py

repl: improved object option value validator

---

uhu/repl/helpers.py

repl: added possibility to edit symmetric object options

---

uhu/updatehub/http.py

http: added separated handler for connection timeout error

---

README.md

README: updates travis badge

---

uhu/repl/helpers.py

Signed-off-by: Christian Tavares <christian.tavares@ossystems.com.br>

Remove the unusable prompt function

---

tests/test_config.py
uhu/config.py
uhu/core/utils.py
uhu/utils.py

Signed-off-by: Christian Tavares <christian.tavares@ossystems.com.br>

Remove mandatory private key to generate package

---

tests/cli/test_package.py
uhu/cli/package.py
uhu/core/objects.py

Bug fix for rejecting object duplicates.

Duplicate object rejection

---

setup.cfg

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

setup.cfg: Raise prompt-toolkit dependency range to 4.0.0

---

uhu/core/_object.py
uhu/core/delta.py
uhu/core/modes.py

Signed-off-by: Jonathas-Conceicao <jonathas.conceicao@ossystems.com.br>

Add support for archiving raw-delta object
